export class ApiStrings  {
    public static LOGIN :string = 'login';
    public static REGISTRATION  :string = 'signUp';
    public static EDUCATION :string= 'education';
    public static WORK_EXPERIENCE:string = 'workExperience';
    public static CERTIFICATES:string = 'certificates';
    public static TAKING_CLASSES:string = 'takingClasses';
    public static CONDUCTING_CLASSES:string = 'conductingClasses';
    public static MENTORING:string = 'mentoring';
    public static WRITINGS:string = 'writings';
    public static CONFERENCES:string = 'conferences';
    public static AWARDS:string = 'awards';
    public static RECOGNIZED_EXPERTISE:string = 'recognizedExpertise';
    public static PATENTS:string = 'patents';
    public static LANGUAGES:string = 'languages';
    public static LEISURE_TRAVEL:string = 'leisureTravel';
    public static TOOLS:string = 'tools';
    public static SKILLS:string = 'skills';
    public static POINTS:string = 'points';
    public static DEEDS:string = 'deeds';
    public static CHARTS:string = 'chart';
    public static SCORES:string = 'scores';
    public static HONORS:string = 'honors';
    public static DASHBOARD:string = 'dashboard';
    public static USER:string = 'user';
    public static API:string = 'api';
};